services:
  app:
    image: maven:3.9.9-eclipse-temurin-21
    working_dir: /workspace
    command: mvn -DskipTests spring-boot:run
    volumes:
      - ./:/workspace
      - maven-cache:/root/.m2
    environment:
      SPRING_DOCKER_COMPOSE_ENABLED: "false"
      SPRING_DEVTOOLS_RESTART_ENABLED: "true"
      SPRING_DEVTOOLS_RESTART_POLL_INTERVAL: "1s"
      SPRING_DEVTOOLS_RESTART_QUIET_PERIOD: "400ms"

volumes:
  maven-cache:
